### PR TITLE
Add audit reports for zkSync, Mantle, Linea

### PR DESCRIPTION
**Pull request by arwer13**
Also move previous (Arbitrum and Optimism) reports to "L2" subdirectory.

### CODE REVIEW

**Review by TheDZhon — CHANGES_REQUESTED** [review]
Thank you for putting everything together. +1: 

I'd suggest having a separate README file for those to preserve context; could you please add it?

**Comment by arwer13** [comment]
Added links to the PDFs under a separate top-level header.

**Review by TheDZhon — APPROVED** [review]
GM, @arwer13 

Thank you for the PR and effort you've done! :+1: 

:pray:  Please pay attention to the latest commit, as I believe there were a few inconsistencies: https://github.com/lidofinance/audits/pull/54/commits/5ca7ddca3c3d3758c077c8e2a410dd09d77bbbac

**Review by grstepanov — APPROVED** [review]
lgtm!

**Pull request merged**
